### ISSUE TITLE
table -> +actions() -> change label

### ISSUE THREAD

**Issue by brsgina** [spxbhuhb/zakadabar-stack#62]
I would like to add actions() to my table, but with a different label, not always Details.

**Comment by toth-istvan-zoltan** [comment]
Added in 2021.8.30, recipe:

[Custom Table Actions](https://zakadabar.io/en/Cookbook/browser/table/action/recipe.md#Custom-Table-Actions)

As for the colors: table actions should be the primary colors of the theme (which is the default). If you want something else,  override `zkTableStyles.actionEntry`, see [Vertical Table Cell Border](https://zakadabar.io/en/Cookbook/browser/table/border/vertical/recipe.md#Vertical-Table-Cell-Border) for example.
