### ISSUE TITLE
.apk file download from web

### ISSUE THREAD

**Issue by brsgina** [spxbhuhb/zakadabar-stack#67]
I would like to download the mobile applications .apk file from a web page.

**Comment by toth-istvan-zoltan** [comment]
Put it in `./var/static` and serve as any other static file.

See: [HTTP Server](https://zakadabar.io/en/Documentation/guides/backend/HttpServer.md#HTTP-Server) for more information and the [Using Font Files](https://zakadabar.io/en/Cookbook/browser/css/fontfiles/recipe.md#Using-Font-Files) for example.
