### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by SimplexionJulcsi** [spxbhuhb/zakadabar-stack#69]
On the pages which aren't open from the navigation drawer, usually we use BACK button on the bottom to navigate to the pevious page. But on the pages that contain a table, it looks very strange. It would be better to have breadcrumbs on the top of every page. In this case the BACK button wouldn't be nessesary on any page.

**Comment by toth-istvan-zoltan** [comment]
This needs much planning and it really depends on the actual application. I will close this issue for now and think about it after the declarative UI milestone.
