### ISSUE TITLE
Table state save - search, add, export disappear from page header

### ISSUE THREAD

**Issue by brsgina** [spxbhuhb/zakadabar-stack#77]
When I navigate back to a page (which contains a table only), the search field, the export button and the add button are disappear from the page header. They come back with page refresh only.

**Comment by toth-istvan-zoltan** [comment]
How is this table saved and restored? The application title is updated from `ZkTable.onResume` by calling `setAppTitleBar`. It should update the title but it really depends how the save/restore is implemented.
