### ISSUE TITLE
Dispatcher.kt indexing bug in Schedule lib

### ISSUE THREAD

**Issue by brsgina** [spxbhuhb/zakadabar-stack#97]
` val index = pendingJobs.binarySearch { it.startAt !!.compareTo(startAt)   }.absoluteValue `
 `  pendingJobs.add(index, entry)`

when index is -1, the absolute value is 1, but if the list is empty, you have to add to 0. index

So I got this error:
IndexOutOfBoundsException: Index: 1, Size: 0

**Comment by toth-istvan-zoltan** [comment]
fixed in 2022.2.25
